.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit fangs rollback" 1  "snakepit fangs rollback " 
.SH NAME
snakepit fangs rollback \- ⏪ Rollback modifications to a module
.SH SYNOPSIS
\fBsnakepit fangs rollback\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIMODULE\fR> 
.SH DESCRIPTION
⏪ Rollback modifications to a module
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIMODULE\fR>
Module name
