.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snake discover" 1  "snakepit snake discover " 
.SH NAME
snakepit snake discover \- 📡 Discover connected Android devices
.SH SYNOPSIS
\fBsnakepit snake discover\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
📡 Discover connected Android devices
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
