.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snake profile" 1  "snakepit snake profile " 
.SH NAME
snakepit snake profile \- 📈 Profile performance on device
.SH SYNOPSIS
\fBsnakepit snake profile\fR <\fB\-d\fR|\fB\-\-device\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fISCRIPT\fR> 
.SH DESCRIPTION
📈 Profile performance on device
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Device ID
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISCRIPT\fR>
Script to profile
