.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit fangs cache" 1  "snakepit fangs cache " 
.SH NAME
snakepit fangs cache \- 💾 Add caching to a function
.SH SYNOPSIS
\fBsnakepit fangs cache\fR [\fB\-t\fR|\fB\-\-ttl\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIMODULE\fR> <\fIFUNCTION\fR> 
.SH DESCRIPTION
💾 Add caching to a function
.SH OPTIONS
.TP
\fB\-t\fR, \fB\-\-ttl\fR \fI<TTL>\fR [default: 3600]
TTL in seconds
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIMODULE\fR>
Module name
.TP
<\fIFUNCTION\fR>
Function name
