.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snake disconnect" 1  "snakepit snake disconnect " 
.SH NAME
snakepit snake disconnect \- 🔌 Disconnect from WiFi device
.SH SYNOPSIS
\fBsnakepit snake disconnect\fR [\fB\-p\fR|\fB\-\-port\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIIP\fR> 
.SH DESCRIPTION
🔌 Disconnect from WiFi device
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-port\fR \fI<PORT>\fR [default: 5555]
Port (default: 5555)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIIP\fR>
IP address of device
