.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit daemon restart" 1  "snakepit daemon restart " 
.SH NAME
snakepit daemon restart \- 🔄 Restart the daemon
.SH SYNOPSIS
\fBsnakepit daemon restart\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
🔄 Restart the daemon
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
