.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit install" 1  "snakepit install " 
.SH NAME
snakepit install \- 📦 Install a Python package
.SH SYNOPSIS
\fBsnakepit install\fR [\fB\-v\fR|\fB\-\-version\fR] [\fB\-d\fR|\fB\-\-dev\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
📦 Install a Python package
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-version\fR \fI<VERSION>\fR
Specific version to install
.TP
\fB\-d\fR, \fB\-\-dev\fR
Install as development dependency
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package name to install
