.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit env destroy" 1  "snakepit env destroy " 
.SH NAME
snakepit env destroy \- 💥 Remove the persistent environment
.SH SYNOPSIS
\fBsnakepit env destroy\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
💥 Remove the persistent environment
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
