.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit daemon status" 1  "snakepit daemon status " 
.SH NAME
snakepit daemon status \- 📊 Show daemon status
.SH SYNOPSIS
\fBsnakepit daemon status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
📊 Show daemon status
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
