.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snapshot restore" 1  "snakepit snapshot restore " 
.SH NAME
snakepit snapshot restore \- ⏪ Restore a snapshot
.SH SYNOPSIS
\fBsnakepit snapshot restore\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
⏪ Restore a snapshot
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Snapshot ID
