.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit ui" 1  "snakepit ui " 
.SH NAME
snakepit ui \- 🖥️  Launch the visual dependency dashboard
.SH SYNOPSIS
\fBsnakepit ui\fR [\fB\-p\fR|\fB\-\-port\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
🖥️  Launch the visual dependency dashboard
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-port\fR \fI<PORT>\fR [default: 8080]
Port to run the dashboard on
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
