.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snake logs" 1  "snakepit snake logs " 
.SH NAME
snakepit snake logs \- 📜 Stream logs from device
.SH SYNOPSIS
\fBsnakepit snake logs\fR <\fB\-d\fR|\fB\-\-device\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
📜 Stream logs from device
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Device ID
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
