.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit init" 1  "snakepit init " 
.SH NAME
snakepit init \- 🚀 Initialize a new project
.SH SYNOPSIS
\fBsnakepit init\fR [\fB\-h\fR|\fB\-\-help\fR] [\fINAME\fR] 
.SH DESCRIPTION
🚀 Initialize a new project
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fINAME\fR]
Project name
