.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit env path" 1  "snakepit env path " 
.SH NAME
snakepit env path \- 📍 Show the Python path for shell integration
.SH SYNOPSIS
\fBsnakepit env path\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
📍 Show the Python path for shell integration
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
