.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit fangs fork" 1  "snakepit fangs fork " 
.SH NAME
snakepit fangs fork \- 🍴 Fork a module for modification
.SH SYNOPSIS
\fBsnakepit fangs fork\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIMODULE\fR> 
.SH DESCRIPTION
🍴 Fork a module for modification
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIMODULE\fR>
Module name
