.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit uninstall" 1  "snakepit uninstall " 
.SH NAME
snakepit uninstall \- 🗑️  Uninstall a Python package
.SH SYNOPSIS
\fBsnakepit uninstall\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
🗑️  Uninstall a Python package
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package name to uninstall
