.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit daemon" 1  "snakepit daemon " 
.SH NAME
snakepit daemon \- 👹 Daemon management
.SH SYNOPSIS
\fBsnakepit daemon\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
👹 Daemon management
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
snakepit daemon\-start(1)
▶️  Start the snakepit daemon
.TP
snakepit daemon\-stop(1)
⏹️  Stop the snakepit daemon
.TP
snakepit daemon\-status(1)
📊 Show daemon status
.TP
snakepit daemon\-restart(1)
🔄 Restart the daemon
.TP
snakepit daemon\-test(1)
🧪 Simulate a missing module for testing
.TP
snakepit daemon\-config(1)
⚙️  Configure daemon settings
.TP
snakepit daemon\-help(1)
Print this message or the help of the given subcommand(s)
