.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit fangs custom" 1  "snakepit fangs custom " 
.SH NAME
snakepit fangs custom \- 💉 Inject custom code into a function
.SH SYNOPSIS
\fBsnakepit fangs custom\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIMODULE\fR> <\fIFUNCTION\fR> <\fICODE\fR> 
.SH DESCRIPTION
💉 Inject custom code into a function
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIMODULE\fR>
Module name
.TP
<\fIFUNCTION\fR>
Function name
.TP
<\fICODE\fR>
Python code to inject
