.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit venv create" 1  "snakepit venv create " 
.SH NAME
snakepit venv create \- ✨ Create a new virtual environment
.SH SYNOPSIS
\fBsnakepit venv create\fR [\fB\-p\fR|\fB\-\-python\-version\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
✨ Create a new virtual environment
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-python\-version\fR \fI<PYTHON_VERSION>\fR
Python version to use
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Virtual environment name
