.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit sync" 1  "snakepit sync " 
.SH NAME
snakepit sync \- 🔄 Sync dependencies from requirements file
.SH SYNOPSIS
\fBsnakepit sync\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
🔄 Sync dependencies from requirements file
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
