.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit venv activate" 1  "snakepit venv activate " 
.SH NAME
snakepit venv activate \- ⚡ Activate a virtual environment
.SH SYNOPSIS
\fBsnakepit venv activate\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
⚡ Activate a virtual environment
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Virtual environment name
