.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit env init" 1  "snakepit env init " 
.SH NAME
snakepit env init \- 🏗️  Create or recreate the persistent environment
.SH SYNOPSIS
\fBsnakepit env init\fR [\fB\-p\fR|\fB\-\-python\-version\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
🏗️  Create or recreate the persistent environment
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-python\-version\fR \fI<PYTHON_VERSION>\fR
Python version to use
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
