.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snake connect" 1  "snakepit snake connect " 
.SH NAME
snakepit snake connect \- 📶 Connect to device via WiFi
.SH SYNOPSIS
\fBsnakepit snake connect\fR [\fB\-p\fR|\fB\-\-port\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIIP\fR> 
.SH DESCRIPTION
📶 Connect to device via WiFi
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-port\fR \fI<PORT>\fR [default: 5555]
Port (default: 5555)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIIP\fR>
IP address of device
