.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit fangs log" 1  "snakepit fangs log " 
.SH NAME
snakepit fangs log \- 📝 Add logging to a function
.SH SYNOPSIS
\fBsnakepit fangs log\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIMODULE\fR> <\fIFUNCTION\fR> 
.SH DESCRIPTION
📝 Add logging to a function
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIMODULE\fR>
Module name
.TP
<\fIFUNCTION\fR>
Function name
