.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit fix" 1  "snakepit fix " 
.SH NAME
snakepit fix \- 🔧 Fix a broken command by analyzing its error output
.SH SYNOPSIS
\fBsnakepit fix\fR [\fB\-h\fR|\fB\-\-help\fR] [\fICOMMAND\fR] 
.SH DESCRIPTION
🔧 Fix a broken command by analyzing its error output
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fICOMMAND\fR]
The command to run and analyze (use \-\- to separate args)
