.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit fangs mock" 1  "snakepit fangs mock " 
.SH NAME
snakepit fangs mock \- 🎭 Mock function return value
.SH SYNOPSIS
\fBsnakepit fangs mock\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIMODULE\fR> <\fIFUNCTION\fR> <\fIVALUE\fR> 
.SH DESCRIPTION
🎭 Mock function return value
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIMODULE\fR>
Module name
.TP
<\fIFUNCTION\fR>
Function name
.TP
<\fIVALUE\fR>
Return value (Python expression)
