.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snake install" 1  "snakepit snake install " 
.SH NAME
snakepit snake install \- 📦 Install package on device
.SH SYNOPSIS
\fBsnakepit snake install\fR <\fB\-d\fR|\fB\-\-device\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
📦 Install package on device
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Device ID
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package name
