.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snake test" 1  "snakepit snake test " 
.SH NAME
snakepit snake test \- 🧪 Run tests on device
.SH SYNOPSIS
\fBsnakepit snake test\fR <\fB\-d\fR|\fB\-\-device\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fITEST_FILE\fR> 
.SH DESCRIPTION
🧪 Run tests on device
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Device ID
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITEST_FILE\fR>
Test file
