.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit list" 1  "snakepit list " 
.SH NAME
snakepit list \- 📋 List installed packages with sizes
.SH SYNOPSIS
\fBsnakepit list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
📋 List installed packages with sizes
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
