.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit daemon start" 1  "snakepit daemon start " 
.SH NAME
snakepit daemon start \- ▶️  Start the snakepit daemon
.SH SYNOPSIS
\fBsnakepit daemon start\fR [\fB\-d\fR|\fB\-\-daemon\fR] [\fB\-c\fR|\fB\-\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
▶️  Start the snakepit daemon
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-daemon\fR
Run in background
.TP
\fB\-c\fR, \fB\-\-config\fR \fI<CONFIG>\fR
Configuration file path
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
