.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit search" 1  "snakepit search " 
.SH NAME
snakepit search \- 🔍 Search for packages on PyPI
.SH SYNOPSIS
\fBsnakepit search\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIQUERY\fR> 
.SH DESCRIPTION
🔍 Search for packages on PyPI
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIQUERY\fR>
Query string
