.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit venv list" 1  "snakepit venv list " 
.SH NAME
snakepit venv list \- 📋 List all virtual environments
.SH SYNOPSIS
\fBsnakepit venv list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
📋 List all virtual environments
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
