.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit show" 1  "snakepit show " 
.SH NAME
snakepit show \- 🔎 Show package details
.SH SYNOPSIS
\fBsnakepit show\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
🔎 Show package details
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package name
