.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit env status" 1  "snakepit env status " 
.SH NAME
snakepit env status \- 📊 Show the persistent environment status and path
.SH SYNOPSIS
\fBsnakepit env status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
📊 Show the persistent environment status and path
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
