.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "snakepit snake" 1  "snakepit snake " 
.SH NAME
snakepit snake \- 🐍 Solid Snake — test on Android devices
.SH SYNOPSIS
\fBsnakepit snake\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
🐍 Solid Snake — test on Android devices
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
snakepit snake\-discover(1)
📡 Discover connected Android devices
.TP
snakepit snake\-connect(1)
📶 Connect to device via WiFi
.TP
snakepit snake\-disconnect(1)
🔌 Disconnect from WiFi device
.TP
snakepit snake\-install(1)
📦 Install package on device
.TP
snakepit snake\-test(1)
🧪 Run tests on device
.TP
snakepit snake\-profile(1)
📈 Profile performance on device
.TP
snakepit snake\-logs(1)
📜 Stream logs from device
.TP
snakepit snake\-help(1)
Print this message or the help of the given subcommand(s)
